### ISSUE TITLE
borderRadius not working properly

### ISSUE THREAD

**Issue by nitish1099** [tomzaku/react-native-shimmer-placeholder#17]
The borderRadius style when applied doesn't set the correct border radius

**Comment by kayzenkayzen** [comment]
some issue, works ok on ios, but on android is alwalys very rounded!

**Comment by tomzaku** [comment]
Could you give me the code?
Did you apply "backgroundColorBehindBorder" props?

**Comment by bLuka** [comment]
@tomzaku When `this.props.style.borderRadius !== 0`, the box is completely rounded on Android.

Not tested yet on iOS.

```
<Shimmer
    style={{borderRadius: 5, width: 100, height: 100}}
    autoRun={true}
    visible={false} />
```

![screenshot](https://user-images.githubusercontent.com/36578146/47586394-5de24d80-d960-11e8-8ae2-0ed8561c27b3.png)

The issue is same width negative radiuses.

EDIT: after a quick check, it may come from this:
https://github.com/tomzaku/react-native-shimmer-placeholder/blob/ffb9b4536c99f9b0eadddeec85baa0ef6e1e64eb/lib/ShimmerPlaceholder.js#L101

I'll give a try.

**Comment by bLuka** [comment]
I found it. I'll submit a PR.
